---
- name: Rules unconfigured
  file:
    path: "{{ ipnat_config_dir }}/50_{{ item.id }}"
    state: absent
  with_items: "{{ rules }}"
  when: item.state is defined and item.state == 'absent'

- name: Rules configured
  template:
    src: templates/50_newrule
    dest: "{{ ipnat_config_dir }}/50_{{ item.id }}"
    backup: no
    mode: 0644
    trim_blocks: no
    validate: /usr/sbin/ipnat -n -f %s
  with_items: "{{ rules }}"
  when: item.state is not defined or item.state == 'present'

- name: NAT refreshed
  service:
    name: site/setup/ipnat
    state: reloaded
