---
- name: IPV4 forwarding enabled
  shell: routeadm -u -e ipv4-forwarding

- name: NAT rules
  register: nat_rules
  template:
    src: templates/ipnat.conf.j2
    dest: /etc/ipf/ipnat.conf
    backup: yes
    mode: 0644

- name: Route service enabled
  service:
    name: route
    enabled: yes

- name: IPFilter service enabled
  service:
    name: ipfilter
    enabled: yes

- name: IPFilter rules loaded
  service:
    name: ipfilter
    state: reloaded
  when: nat_rules.changed
