---
- name: Images imported
  loop: "{{ query('inventory_hostnames', 'all:!baremetal') | sort }}"
  vars:
    uuid: "{{ hostvars[item].vmadm_image_uuid }}"
  loop_control:
    label: "{{ uuid }}"
  imgadm:
    uuid: "{{ uuid }}"
    state: imported
