---
- name: Secrets loaded
  include_vars: secrets.yml

- name: ZFS compression and dedup enabled
  zfs:
    name: zones
    extra_zfs_properties:
      compress: lz4
      dedup: yes
    state: present

- name: ZFS dedup disabled on swap
  zfs:
    name: zones/swap
    extra_zfs_properties:
      dedup: no
    state: present

- name: ZFS global data dataset created
  zfs:
    name: "{{ global_data_dataset }}"
    state: present

- name: etherstub enabled
  register: etherstub
  lineinfile:
    path: /usbkey/config
    regexp: '^etherstub='
    line: 'etherstub=stub0'

- name: keymap set
  register: keymap
  lineinfile:
    path: /usbkey/config
    regexp: '^default_keymap='
    line: 'default_keymap=uk'

- name: search domain set
  register: keymap
  lineinfile:
    path: /usbkey/config
    regexp: '^dns_domain='
    line: 'dns_domain='

- name: Config folder created
  file:
    path: /usbkey/config.inc/
    state: directory

- name: SMF folder created
  file:
    path: /opt/custom/smf
    state: directory

- name: authorized_keys file added
  copy:
    content: "{{ ssh_authkeys }}"
    dest: /usbkey/config.inc/authorized_keys
    mode: 0400

- name: authorized_keys configured
  register: authkeys
  lineinfile:
    path: /usbkey/config
    regexp: '^root_authorized_keys_file='
    line: 'root_authorized_keys_file=authorized_keys'

- name: Config reloaded
  shell: sysinfo -u
  when: etherstub.changed or authkeys.changed or keymap.changed

- name: PasswordAuthentication disabled
  lineinfile:
    path: /usbkey/ssh/sshd_config
    regexp: 'PasswordAuthentication '
    line: 'PasswordAuthentication no'

- name: Password prompt disabled
  lineinfile:
    path: /usbkey/ssh/sshd_config
    regexp: 'KbdInteractiveAuthentication'
    line: 'KbdInteractiveAuthentication no'

- name: GSSAPI disabled
  lineinfile:
    path: /usbkey/ssh/sshd_config
    regexp: 'GSSAPIAuthentication '
    line: 'GSSAPIAuthentication no'

- name: X11Forwarding disabled
  lineinfile:
    path: /usbkey/ssh/sshd_config
    regexp: 'X11Forwarding '
    line: 'X11Forwarding no'

- include: routing.yml

- include: images.yml

- include: zones.yml
