---
- name: Secrets loaded
  tags:
    - always
  include_vars: secrets.yml

- import_tasks: config.yml

- vars:
    install: yes
  import_role:
    name: ipfilter

- vars:
    install: yes
  import_role:
    name: ipnat

- import_tasks: rsyslog.yml

- import_tasks: zfs.yml

- import_tasks: images.yml

- import_tasks: zones.yml
