---
- name: etherstub
  lineinfile:
    path: /usbkey/config
    regexp: '^etherstub='
    line: 'etherstub=stub0'
    validate: 'sysinfo -u'

- name: authorized_keys file
  copy:
    src: authorized_keys
    dest: /usbkey/config.inc/
    mode: 0400

- name: authorized_keys config step
  lineinfile:
    path: /usbkey/config
    regexp: '^root_authorized_keys_file='
    line: 'root_authorized_keys_file=authorized_keys'
    validate: 'sysinfo -u'

- name: PasswordAuthentication disabled
  lineinfile:
    path: /usbkey/ssh/sshd_config
    regexp: 'PasswordAuthentication '
    line: 'PasswordAuthentication no'

- name: Password prompt disabled
  lineinfile:
  regexp: 'KbdInteractiveAuthentication'
    line: 'KbdInteractiveAuthentication no'

- name: GSSAPI disabled
  lineinfile:
    path: /usbkey/ssh/sshd_config
    regexp: 'GSSAPIAuthentication '
    line: 'GSSAPIAuthentication no'

- name: X11Forwarding disabled
  lineinfile:
    path: /usbkey/ssh/sshd_config
    regexp: 'X11Forwarding '
    line: 'X11Forwarding no'