---
- name: Secrets loaded
  include_vars: secrets.yml

- name: ZFS compression and dedup enabled
  zfs:
    name: zones
    extra_zfs_properties:
      compress: lz4
      dedup: yes
    state: present

- name: ZFS dedup disabled on swap
  zfs:
    name: zones/swap
    extra_zfs_properties:
      dedup: no
    state: present

- name: ZFS global data dataset created
  zfs:
    name: "{{ global_data_dataset }}"
    state: present

- name: etherstub enabled
  register: etherstub
  lineinfile:
    path: /usbkey/config
    regexp: '^etherstub='
    line: 'etherstub=stub0'

- name: keymap set
  register: keymap
  lineinfile:
    path: /usbkey/config
    regexp: '^default_keymap='
    line: 'default_keymap=uk'

- name: search domain set
  register: keymap
  lineinfile:
    path: /usbkey/config
    regexp: '^dns_domain='
    line: 'dns_domain=localdomain'

- name: Config folder created
  file:
    path: /usbkey/config.inc/
    state: directory

- name: SMF folder created
  file:
    path: /opt/custom/smf
    state: directory

- name: Binary folder created
  file:
    path: "{{ binary_install_dir }}"
    state: directory

- name: Config folder created
  file:
    path: "{{ config_dir }}"
    state: directory

- name: authorized_keys file added
  copy:
    content: "{{ ssh_authkeys }}"
    dest: /usbkey/config.inc/authorized_keys
    mode: 0400

- name: authorized_keys configured
  register: authkeys
  lineinfile:
    path: /usbkey/config
    regexp: '^root_authorized_keys_file='
    line: 'root_authorized_keys_file=authorized_keys'

- name: SSHD config persistent
  copy:
    remote_src: yes
    mode: preserve
    src: /etc/ssh/sshd_config
    dest: /usbkey/ssh/

- name: System rebooted
  command: shutdown -y -g5 -i6
  when: etherstub.changed or authkeys.changed or keymap.changed

- name: System online
  wait_for_connection:
    connect_timeout: 20
    sleep: 10
    delay: 20
    timeout: 300
  when: etherstub.changed or authkeys.changed or keymap.changed

- include: routing.yml

- include: images.yml

- include: zones.yml
