---
- name: Rsyslog config folder created
  file:
    path: /opt/custom/etc/rsyslog.d
    state: directory

- name: Rsyslog config set
  register: rsyslog_config_global
  copy:
    content: "*.*     @{{ address }}:514;RSYSLOG_SyslogProtocol23Format"
    dest: /opt/custom/etc/rsyslog.d/00-telegraf.conf
    mode: 0644

- name: Rsyslog reloaded
  service:
    name: system-log
    state: reloaded
  when: rsyslog_config_global.changed
