---
- name: Zones deployed
  loop: "{{ query('inventory_hostnames', 'all:!baremetal') | sort }}"
  loop_control:
    label: "{{ itemvars.inventory_hostname }}"
    loop_var: zone_name
  vars:
    itemvars: "{{ hostvars[zone_name] }}"
    default_nics:
      - nic_tag: stub0
        ip: "{{ itemvars.address }}"
        netmask: 255.255.255.0
        gateway: "{{ gateway_address }}"
        allow_ip_spoofing: yes
  include_tasks: zone_deploy.yml
