---
- name: Python installed
  hosts: baremetal
  tags:
    - deploy
  roles:
    - role: python

- name: Baremetal configured
  hosts: baremetal
  roles:
    - role: baremetal

- name: "abstruse: Traefik configured"
  hosts: baremetal
  tags:
    - deploy
    - redeploy
    - traefik
  vars:
    frontends:
      - name: abstruse
        backend: abstruse
        rule: "Host:ci.m1cr0man.com"
        state: present
    backends:
      - name: abstruse
        id: prod
        address: 10.0.0.20
        port: 6500
        weight: 1
        state: present
  roles:
    - role: traefik

- name: "cianky: NAT configured"
  hosts: baremetal
  tags:
    - deploy
    - redeploy
    - cianky
  vars:
    rules:
      - id: cianky_mc
        src_port: 25570
        dest_port: 25565
        dest_addr: 10.0.0.103
        state: present
      - id: cianky_ssh
        src_port: 2303
        dest_port: 22
        dest_addr: 10.0.0.103
        state: present
  roles:
    - role: ipnat
