---
- name: Dataset created
  hosts: baremetal
  tags:
    - deploy
  tasks:
    - zfs:
        name: "{{ global_data_dataset }}/ca4011"
        state: present

- name: Zone deployed
  hosts: ca4011
  gather_facts: no
  vars:
    zone: "{{ hostvars.ca4011 }}"
    filesystems:
      - type: lofs
        source: "/{{ global_data_dataset }}/ca4011"
        target: "/ca4011"
        options:
          - nodevice
  roles:
    - role: zone
      delegate_to: "{{ groups.baremetal[0] }}"

- name: Zone configured
  hosts: ca4011
  tasks:
    - name: Gather facts
      tags:
        - deploy
        - redeploy
      setup: {}
  roles:
    # - role: basic
    - role: ssh
    - role: rsyslog

- name: Traefik configured
  hosts: baremetal
  tags:
    - deploy
    - redeploy
    - traefik
  vars:
    frontends:
      - name: ca4011_project
        backend: ca4011_project
        rule: "Host:ca4011.m1cr0man.com,www.ca4011.m1cr0man.com"
        state: present
    backends:
      - name: ca4011_project
        id: prod
        address: 10.0.0.52
        port: 8080
        weight: 1
        state: present
  roles:
    - role: traefik

- name: Dataset deleted
  hosts: baremetal
  tags:
    - destroy
  tasks:
    - zfs:
        name: "{{ global_data_dataset }}/ca4011"
        state: absent
