---
- name: Dataset created
  hosts: baremetal
  tags:
    - deploy
  tasks:
    - zfs:
        name: "{{ global_data_dataset }}/khargi_mc"
        state: present

- name: Zone deployed
  hosts: khargi_mc
  gather_facts: no
  vars:
    zone: "{{ hostvars.khargi_mc }}"
    filesystems:
      - type: lofs
        source: "/{{ global_data_dataset }}/khargi_mc"
        target: "/khargi_mc"
        options:
          - nodevice
    ports:
      - id: khargi_mc
        src: 25575
        dest: 25575
  roles:
    - role: zone
      delegate_to: "{{ groups.baremetal[0] }}"

- name: Zone python
  hosts: khargi_mc
  gather_facts: no
  tags:
    - deploy
  roles:
    - role: python

- name: Dataset deleted
  hosts: baremetal
  tags:
    - destroy
  tasks:
    - zfs:
        name: "{{ global_data_dataset }}/khargi_mc"
        state: absent

- name: Zone configured
  hosts: khargi_mc
  vars:
    minecraft_data_dir: /khargi_mc
    minecraft_server_jar: forge-1.12.2-14.23.5.2823-universal.jar
    modpack: 'http://10.0.0.5:9000/public/Khargis-Khonundrum-Server-1.0.5.zip'
  roles:
    - role: basic
    - role: hostsfile
    - role: ssh
    - role: rsyslog
    - role: minecraft
