---
- name: Dataset created
  hosts: baremetal
  tags:
    - deploy
  tasks:
    - zfs:
        name: "{{ global_data_dataset }}/khargi_mc"
        state: present

- name: Zone deployed
  hosts: khargi_mc
  gather_facts: no
  vars:
    zone: "{{ hostvars.khargi_mc }}"
    filesystems:
      - type: lofs
        source: "/{{ global_data_dataset }}/khargi_mc"
        target: "/khargi_mc"
        options:
          - nodevice
    ports:
      - id: khargi_mc
        src: 25575
        dest: 25565
  roles:
    - role: zone
      delegate_to: "{{ groups.baremetal[0] }}"

- name: Zone python
  hosts: khargi_mc
  gather_facts: no
  tags:
    - deploy
  roles:
    - role: python

- name: Zone configured
  hosts: khargi_mc
  vars:
    minecraft_data_dir: /khargi_mc
    minecraft_server_jar: minecraft_server.1.12.2.jar
    modpack: 'https://media.forgecdn.net/files/2658/240/FTBRevelationServer_2.7.0.zip'
    modpack_setup: |
      bash ./FTBInstall.sh
  roles:
    - role: basic
    - role: ssh
    - role: rsyslog
    - role: minecraft

- name: Dataset deleted
  hosts: baremetal
  tags:
    - destroy
  tasks:
    - zfs:
        name: "{{ global_data_dataset }}/khargi_mc"
        state: absent
