---
- name: Install python on bare metal
  hosts: baremetal
  gather_facts: no
  roles:
    - role: python

- name: Configure bare metal
  hosts: baremetal
  roles:
    - role: ssh
    - role: baremetal
    - role: hostsfile
    - role: docker

- name: Install python on zones
  hosts: all:!baremetal
  gather_facts: no
  roles:
    - role: python

- name: Basic zone config
  hosts: all:!baremetal
  roles:
    - role: ssh
    - role: basic
    - role: rsyslog
    - role: hostsfile

- name: Build packages
  hosts: builder
  roles:
    - role: rsyncd
    - role: telegraf
    - role: influx
    - role: chronograf
    - role: traefik

- name: Configure baremetal services
  hosts: baremetal
  roles:
    - role: telegraf
    - role: traefik

- name: Configure blog
  hosts: blog
  roles:
    - role: blog

- name: Configure Minecraft servers
  hosts: minecraft
  roles:
    - role: basic
    - role: hostsfile
    - role: minecraft
