---
- name: Install python on bare metal
  hosts: baremetal
  gather_facts: no
  roles:
    - role: python

- name: Configure bare metal
  hosts: baremetal
  roles:
    - role: baremetal
    - role: hostsfile

- name: Install python on zones
  hosts: all:!baremetal
  gather_facts: no
  roles:
    - role: python

- name: Basic zone config
  hosts: all:!baremetal
  roles:
    - role: zone
    - role: hostsfile

- name: Build packages
  hosts: builder
  roles:
    - role: rsyncd
    - role: telegraf

- name: Configure metrics store
  hosts: metrics
  roles:
    - role: influx
    - role: chronograf

- name: Configure telegraf
  hosts: baremetal
  roles:
    - role: telegraf

- name: Configure blog
  hosts: blog
  roles:
    - role: blog

- name: Configure Minecraft servers
  hosts: minecraft
  roles:
    - role: zone
    - role: hostsfile
    - role: minecraft
