---
- name: Install python on bare metal
  hosts: baremetal
  gather_facts: no
  roles:
    - role: python

- name: Configure bare metal
  hosts: baremetal
  roles:
    - role: baremetal
    - role: hostsfile

- name: Install python on gateway
  hosts: gateway
  gather_facts: no
  roles:
    - role: python

- name: Configure gateway
  hosts: gateway
  roles:
    - role: zone
    - role: hostsfile
    - role: gateway

- name: Install python on zones
  hosts: all:!baremetal:!gateway
  gather_facts: no
  roles:
    - role: python

- name: Basic zone config
  hosts: all:!baremetal:!gateway
  roles:
    - role: zone
    - role: hostsfile

- name: Configure builder
  hosts: builder
  roles:
    - role: rsyncd

- name: Configure metrics store
  hosts: metrics
  roles:
    - role: influx

- name: Configure blog
  hosts: blog
  roles:
    - role: blog

- name: Configure Minecraft servers
  hosts: minecraft
  roles:
    - role: zone
    - role: hostsfile
    - role: minecraft
