---
- name: Packages updated
  pkgin:
    update_cache: yes
    full_upgrade: yes

- name: SMF directory exists
  file:
    path: /opt/custom/smf
    state: directory

- name: Rsyslog config set
  register: rsyslog_config_zone
  template:
    src: templates/rsyslog.conf.j2
    dest: /opt/local/etc/rsyslog.conf

- name: Rsyslog reloaded
  service:
    name: rsyslog
    state: reloaded
  when: rsyslog_config_zone.changed
