---
- name: OpenJDK installed
  package:
    name: openjdk8
    state: present

- name: Modpack downloaded
  register: modpack
  get_url:
    url: "{{ modpack }}"
    dest: /opt/minecraft/

- name: Unpack modpack
  when: modpack is changed
  unarchive:
    src: "/opt/minecraft/{{ modpack | basename }}"
    dest: /opt/minecraft/
    remote_src: true
