---
- name: OpenJDK installed
  tags:
    - deploy
  package:
    name: openjdk-8-jre
    state: present

- name: Modpack downloaded
  register: modpack_download
  tags:
    - deploy
    - redeploy
  get_url:
    url: "{{ modpack }}"
    dest: "{{ minecraft_data_dir }}"

- name: Service stopped
  tags:
    - redeploy
  service:
    name: minecraft
    state: stopped
    enabled: no
  when: modpack_download is changed

- name: Server backed up
  tags:
    - redeploy
  archive:
    path: "{{ minecraft_data_dir }}"
    dest: "{{ minecraft_data_dir }}/{{ ansible_hostname }}_minecraft_backup.tar.bz2"
    exclude_path:
      - "{{ minecraft_data_dir }}/*.tar.bz2"
      - "{{ minecraft_data_dir }}/*.zip"
    format: bz2
  when: modpack_download is changed

- name: Old contents removed
  tags:
    - redeploy
  file:
    path: "{{ minecraft_data_dir }}/{{ item }}"
    state: absent
  with_items:
    - mods
    - config
    - crash-reports
    - logs
  when: modpack_download is changed

- name: Unpack modpack
  tags:
    - deploy
    - redeploy
  unarchive:
    src: "{{ modpack_download.dest }}"
    dest: "{{ minecraft_data_dir }}"
    remote_src: true
  when: modpack_download is changed

- name: Set up modpack
  tags:
    - deploy
    - redeploy
  shell: "{{ modpack_setup }}"
  args:
    executable: /bin/bash
    chdir: "{{ minecraft_data_dir }}"
  when: modpack_download is changed and modpack_setup is defined

- name: Eula stub copied
  tags:
    - deploy
  template:
    src: templates/eula.txt
    dest: "{{ minecraft_data_dir }}/eula.txt"
    mode: 0644

- name: Service installed
  tags:
    - deploy
    - redeploy
  template:
    src: templates/minecraft.service
    dest: /etc/systemd/system/minecraft.service
    backup: no
    mode: 0755
  when: brand != 'joyent'

- name: SMF copied
  register: minecraft_smf_file
  tags:
    - deploy
    - redeploy
  template:
    src: templates/minecraft.xml
    dest: /opt/custom/smf/minecraft.xml
    mode: 0644
  when: brand == 'joyent'

- name: SMF installed
  register: minecraft_smf_install
  tags:
    - deploy
    - redeploy
  command: svccfg import minecraft.xml
  args:
    chdir: /opt/custom/smf/
    creates: /var/svc/manifest/site/minecraft.xml
  when: brand == 'joyent' and minecraft_smf_file is changed

- name: Service loaded
  tags:
    - deploy
    - redeploy
  service:
    name: minecraft
    enabled: yes
  when: brand == 'joyent' and minecraft_smf_install is changed

- name: Service started
  tags:
    - deploy
    - redeploy
  systemd:
    name: minecraft
    enabled: yes
    daemon_reload: yes
    state: started
  when: brand != 'joyent'

- name: Service restarted
  tags:
    - deploy
    - redeploy
  service:
    name: minecraft
    state: restarted
    # Also check it's enabled incase it was disabled earlier
    enabled: yes
  when: minecraft_smf_file is not changed and modpack_download is changed
