---
- name: Python already installed
  register: python_bin
  raw: "test -e {{ ansible_python_interpreter }}"
  ignore_errors: yes

- include: joyent.yml
  when: python_bin.rc != 0 and brand == 'joyent'

- include: ubuntu.yml
  when: python_bin.rc != 0 and brand == 'lx'
