---
- name: Install directory exists
  tags:
    - deploy
  file:
    path: "{{ binary_install_dir }}"
    state: directory

- name: Binaries copied
  tags:
    - deploy
    - redeploy
  delegate_to: "{{ inventory_hostname }}"
  synchronize:
    mode: pull
    checksum: yes
    src: "rsync://builder{{ gopath }}/src/github.com/minio/mc/mc"
    dest: "{{ binary_install_dir }}/"
