---
- name: config copied
  register: sshd_config
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    mode: 0644
    validate: bash -c "test '{{ is_gz }}' = 'True' || sshd -t -f %s"

- name: service restarted
  service:
    name: ssh
    state: restarted
  when: sshd_config is changed
