---
- name: config copied
  register: sshd_config
  tags:
    - deploy
    - redeploy
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    mode: 0644
    validate: bash -c "test '{{ is_gz }}' = 'True' || $(test -e /usr/lib/ssh/sshd && echo /usr/lib/ssh/)sshd -t -f %s"

- name: service restarted (Alpine)
  tags:
    - deploy
    - redeploy
  service:
    name: sshd
    state: restarted
  when: sshd_config is changed and ansible_distribution == 'Alpine'

- name: service restarted (others)
  tags:
    - deploy
    - redeploy
  service:
    name: ssh
    state: restarted
  when: sshd_config is changed and ansible_distribution != 'Alpine'
