---
- name: Filters deployed
  import_tasks: install.yml
  when: install is defined and install

- name: Filters configured
  tags:
    - always
  import_tasks: configure.yml
  when: rules is defined
