---
- name: Node key added
  tags:
    - deploy
    - redeploy
  apt_key:
    id: 68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Node repo added
  register: node_repo
  tags:
    - deploy
    - redeploy
  apt_repository:
    repo: deb https://deb.nodesource.com/node_11.x xenial main
    state: present

- name: Apt refreshed
  tags:
    - deploy
    - redeploy
  apt:
    update_cache: yes
  when: node_repo is changed

- name: Dependencies installed
  tags:
    - deploy
    - redeploy
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodejs
    - make
    - g++

- name: M1cr0blog updated
  register: m1cr0blog_install
  tags:
    - deploy
    - redeploy
  npm:
    name: m1cr0blog
    path: "{{ blog_data_dir }}"
    production: yes
    state: latest

- name: Service unit file copied
  register: m1cr0blog_unitfile
  tags:
    - deploy
    - redeploy
  template:
    src: templates/m1cr0blog.service.j2
    dest: /etc/systemd/system/m1cr0blog.service
    mode: 0644

- name: Service loaded
  tags:
    - deploy
    - redeploy
  systemd:
    name: m1cr0blog
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: m1cr0blog_install is changed or m1cr0blog_unitfile is changed
