---
- name: Node key added
  apt_key:
    id: 68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Node repo added
  register: node_repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_11.x xenial main
    state: present

- name: Apt refreshed
  apt:
    update_cache: yes
  when: node_repo is changed

- name: Node installed
  package:
    name: nodejs
    state: present

- name: M1cr0blog updated
  register: m1cr0blog_install
  npm:
    name: m1cr0blog
    path: "{{ m1cr0blog_data_dir }}/app"
    state: latest

- name: Service unit file copied
  register: m1cr0blog_unitfile
  template:
    src: templates/m1cr0blog.service.j2
    dest: /etc/systemd/system/m1cr0blog.service
    mode: 0644

- name: Service loaded
  systemd:
    name: m1cr0blog
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: m1cr0blog_install is changed or m1cr0blog_unitfile is changed
