---
- name: Enable ipv4 forwarding
  shell: routeadm -u -e ipv4-forwarding

- name: Route service enabled
  service:
    name: route
    enabled: true

- name: IPFilter service enabled
  service:
    name: ipfilter
    enabled: true

- name: NAT rules
  template:
    src: templates/ipnat.conf.j2
    dest: /etc/ipf/ipnat.conf
    verify: 'ipnat -l'
    backup: true
    mode: 0644