---
- name: Packages updated
  tags:
    - deploy
    - redeploy
  apt:
    update_cache: yes
    upgrade: full
    autoclean: yes

- name: Packages installed
  tags:
    - deploy
  apt:
    name:
      - unzip
    state: present
