---
- name: Syslog-ng installed
  tags:
    - deploy
    - redeploy
  apt:
    name: syslog-ng
    update_cache: yes
    state: present

- name: Syslog-ng config set
  tags:
    - deploy
    - redeploy
  register: syslog_ng_config_zone
  template:
    src: templates/syslog-ng-log.m1cr0man
    dest: "{{ '/opt/local/' if brand == 'joyent' else '' }}/etc/syslog-ng/syslog-ng-log.m1cr0man"

- name: Syslog-ng reloaded
  tags:
    - deploy
    - redeploy
  service:
    name: syslog-ng
    state: restarted
  when: syslog_ng_config_zone.changed
