---
- name: Gopath exists
  file:
    path: "{{ gopath }}"
    state: directory

- name: System dependencies installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - go
    - git
    - gcc49
    - gmake

- name: Yarn installed
  npm:
    name: yarn
    global: yes
    state: present

- name: Chronograf downloaded
  command: go get github.com/influxdata/chronograf
  args:
    creates: "{{ gopath }}/src/github.com/influxdata/chronograf"

- name: Chronograf built
  command: make
  args:
    chdir: "{{ gopath }}/src/github.com/influxdata/chronograf"
    creates: "{{ gopath }}/src/github.com/influxdata/chronograf/chronograf"
