---
- name: Gopath exists
  file:
    path: "{{ gopath }}"
    state: directory

- name: System dependencies installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - go
    - git
    - gcc49
    - gmake

- name: Influx downloaded
  command: go get github.com/influxdata/influxdb
  args:
    creates: "{{ gopath }}/src/github.com/influxdata/influxdb"

- name: Dependencies downloaded
  command: dep ensure
  args:
    chdir: "{{ gopath }}/src/github.com/influxdata/influxdb"
    creates: "{{ gopath }}/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/influxql"

- name: Influx built
  command: go install ./...
  args:
    chdir: "{{ gopath }}/src/github.com/influxdata/influxdb"
    creates: "{{ gopath }}/bin/influxd"
