---
- name: Gopath exists
  file:
    path: "{{ gopath }}"
    state: directory

- name: System dependencies installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - go
    - git

- name: Influx downloaded
  command: go get github.com/influxdata/influxdb
  args:
    creates: "{{ gopath }}/src/github.com/influxdata/influxdb"

- name: Dependencies downloaded
  command: go get ./influxdb
  args:
    chdir: "{{ gopath }}/src/github.com/influxdata"
    creates: "{{ gopath }}/src/github.com/influxdata/influxql"

- name: Influx built
  command: go install ./influxdb
  args:
    chdir: "{{ gopath }}/src/github.com/influxdata"
    creates: "{{ gopath }}/bin/influxd"
