---
- include: build.yml
  environment:
    GOPATH: "{{ gopath }}"
    GOBIN: "{{ gopath }}/bin"
    PATH: "{{ gopath }}/bin:{{ default_path }}"
  when: inventory_hostname == 'builder'

- include: install.yml
  when: inventory_hostname != 'builder'
