---
- name: "chronograf: Dataset created"
  tags:
    - deploy
  zfs:
    name: "{{ global_data_dataset }}/chronograf"
    state: present

- name: "chronograf: Zone configured"
  vars:
    hostname: chronograf
    address: 10.0.0.3
    image_tag: chronograf:alpine
    vmadm_cpu: 5
    vmadm_ram: 256
    filesystems:
      - type: lofs
        source: "/{{ global_data_dataset }}/chronograf"
        target: /var/lib/chronograf
        options:
          - nodevice
    envvars:
      - "INFLUXDB_URL=http://{{ metrics_address }}:8086"
  include: deploy.yml

- name: "chronograf: Traefik unconfigured"
  tags:
    - destroy
  vars:
    frontends:
      - name: chronograf
        state: absent
    backends:
      - name: chronograf
        id: prod
        state: absent
  import_role:
    name: traefik

- name: "chronograf: Traefik configured"
  tags:
    - deploy
    - redeploy
  vars:
    frontends:
      - name: chronograf
        backend: chronograf
        protect: yes
        rule: "Host:graphs.m1cr0man.com"
        state: present
    backends:
      - name: chronograf
        id: prod
        address: 10.0.0.3
        port: 8888
        weight: 1
        state: present
  import_role:
    name: traefik

- name: "chronograf: Dataset deleted"
  tags:
    - destroy
  zfs:
    name: "{{ global_data_dataset }}/chronograf"
    state: absent
