---
- name: "chronograf: Dataset created"
  tags:
    - deploy
  zfs:
    name: "{{ global_data_dataset }}/chronograf"
    state: present

- name: "chronograf: Zone configured"
  vars:
    hostname: chronograf
    address: 10.0.0.63
    image_tag: chronograf:alpine
    vmadm_cpu: 5
    vmadm_ram: 256
    filesystems:
      - type: lofs
        source: "/{{ global_data_dataset }}/chronograf"
        target: /var/lib/chronograf
        options:
          - nodevice
  include: deploy.yml

- name: "chronograf: Dataset deleted"
  tags:
    - destroy
  zfs:
    name: "{{ global_data_dataset }}/chronograf"
    state: absent
