---
- name: Secrets loaded
  tags:
    - deploy
    - redeploy
  include_vars: secrets.yml

- name: Image source configured
  tags:
    - deploy
  imgadm:
    source: 'https://docker.io'
    type: docker
    state: present

- name: traefik
  tags:
    - traefik
  include_tasks: traefik.yml

- name: influxdb
  tags:
    - influxdb
  include_tasks: influxdb.yml

- name: chronograf
  tags:
    - chronograf
  include_tasks: chronograf.yml

- name: minio
  tags:
    - minio
  include_tasks: minio.yml
