---
- tags:
    - deploy
    - redeploy
  set_fact:
    traefik_config_dir: /etc/traefik

- name: "traefik: Dataset created"
  tags:
    - deploy
  zfs:
    name: "{{ global_data_dataset }}/traefik"
    state: present

- name: "traefik: Configs copied"
  tags:
    - deploy
    - redeploy
  template:
    src: "templates/{{ item }}"
    dest: "/{{ global_data_dataset }}/traefik/{{ item }}"
    backup: no
    mode: 0644
    trim_blocks: no
  with_items:
    - traefik.htpasswd
    - traefik.toml

- name: "traefik: Ansible configs dir created"
  tags:
    - deploy
  file:
    path: "/{{ global_data_dataset }}/traefik/traefik.d"
    state: directory

- name: "traefik: Zone"
  vars:
    hostname: traefik
    address: 10.0.0.4
    image_tag: traefik:alpine
    vmadm_cpu: 25
    vmadm_ram: 256
    filesystems:
      - type: lofs
        source: "/{{ global_data_dataset }}/traefik"
        target: "{{ traefik_config_dir }}"
        options:
          - nodevice
  include: deploy.yml

- name: "traefik: NAT unconfigured"
  tags:
    - destroy
  vars:
    rules:
      - id: traefik
        state: absent
  import_role:
    name: ipnat

- name: "traefik: NAT configured"
  tags:
    - deploy
    - redeploy
  vars:
    rules:
      - id: traefik
        src_port: 80
        dest_port: 80
        dest_addr: 10.0.0.4
        state: present
  import_role:
    name: ipnat

- name: "traefik: Dataset deleted"
  tags:
    - destroy
  zfs:
    name: "{{ global_data_dataset }}/traefik"
    state: absent
