---
- name: Gopath exists
  file:
    path: "{{ gopath }}"
    state: directory

- name: System dependencies installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - go
    - git
    - gcc49
    - gmake

- name: Dep install script copied
  copy:
    src: files/dep_install.sh
    dest: /tmp/
    mode: 0700

- name: Dep installed
  command: /tmp/dep_install.sh
  args:
    creates: "{{ gopath }}/bin/dep"

- name: Telegraf downloaded
  command: go get -d github.com/influxdata/telegraf
  args:
    creates: "{{ gopath }}/src/github.com/influxdata/telegraf"

- name: Custom plugins downloaded
  command: go get -d github.com/m1cr0man/smartos-telegraf-plugins
  args:
    creates: "{{ gopath }}/src/github.com/m1cr0man/smartos-telegraf-plugins"

- name: Inputs configured
  register: telegraf_inputs
  copy:
    src: files/inputs.go
    dest: "{{ gopath }}/src/github.com/influxdata/telegraf/plugins/inputs/all/all.go"

- name: Outputs configured
  register: telegraf_outputs
  copy:
    src: files/outputs.go
    dest: "{{ gopath }}/src/github.com/influxdata/telegraf/plugins/outputs/all/all.go"

- name: Telegraf built
  command: make
  vars:
    telegraf_binary: "{{ gopath }}/src/github.com/influxdata/telegraf/telegraf"
  args:
    chdir: "{{ gopath }}/src/github.com/influxdata/telegraf"
  when: telegraf_inputs is changed or telegraf_outputs is changed or telegraf_binary is not exists
